//
//  DataProvider.swift
//  MyVocabulary
//
//  Created by Ondrej Andrysek on 5/20/18.
//  Copyright © 2018 Ondrej Andrysek. All rights reserved.
//

import Foundation

class DataProvider{
    
    func getArray(lessonID: String, bundle: Int) -> [Word]{
        var arr = [Word]()
        switch bundle {
        case 1:
            arr = createArray(lessonID: lessonID, array: bundle1, arrayForeign: bundle1Foreign)
        case 2:
            arr = createArray(lessonID: lessonID, array: bundle2, arrayForeign: bundle2Foreign)
        case 3:
            arr = createArray(lessonID: lessonID, array: bundle3, arrayForeign: bundle3Foreign)
        case 4:
            arr = createArray(lessonID: lessonID, array: bundle4, arrayForeign: bundle4Foreign)
        case 5:
            arr = createArray(lessonID: lessonID, array: romaji, arrayForeign: hirigana)
        case 6:
            arr = createArray(lessonID: lessonID, array: bundleJapanese1, arrayForeign: bundleJapaneseForeign1)
        case 7:
            arr = createArray(lessonID: lessonID, array: aiueoCzech, arrayForeign: aiueoJapanese)
        case 8:
            arr = createArray(lessonID: lessonID, array: japaneseBasic1Czech, arrayForeign: japaneseBasic1)
        default:
            break
        }
        return arr
    }
    
    func createArray(lessonID: String, array: [String], arrayForeign: [String]) -> [Word]{
        var arr = [Word]()
        for i in 0...array.count - 1{
            let item = array[i]
            let itemForeign = arrayForeign[i]
            let word = Word(lessonID: lessonID, word: item, foreignWord: itemForeign)
            arr.append(word)
        }
        return arr
    }
    
    let bundle1Foreign = ["et barn","en bestefar","en bibliotekar","ei datter","et fisker","et gjest","en journalist","en maler","en mamma","en pappa","et reisebyrå","en sjef","en sønn","ei venninne","bra","de","dere","det","du","fint","fra","gift","ha","han","har","hei","her","hjemme","hun","hva","hvem","hvordan","i","interessant","ja","jeg","med","men","nei","norsk","og","også","så","takk","til","tsjekkisk","velkommen","vi","være"]
    let bundle1 = ["dítě","dědeček","knihovník","dcera","rybář","host","novinář","malíř","maminka","tatínek","cestovní kancelář","vedoucí","syn","kamarádka","dobře","oni","vy","to","ty","dobře","z","ženatý","mít","on","mít","ahoj","zde","doma","ona","co","kdo","jak","v","zajímavý","ano","já","s","ale","ne","norština","a","také","tak","děkuji","k","čeština","vítejte","my","být"]
    
    let bundle2Foreign = [
    "et bibliotek",
    "ei bok",
    "en dag",
    "en frukt",
    "ei lys",
    "en ski",
    "en termos",
    "ei tid",
    "en tur",
    "en TV",
    "ei uke",
    "en venn",
    "allikevel",
    "arbeide",
    "bare",
    "bedre",
    "begynne",
    "bli",
    "bo",
    "da",
    "deg",
    "dette",
    "doven",
    "drikke",
    "eller",
    "forstå",
    "gjore",
    "gå",
    "hete",
    "hjem",
    "hver",
    "hvor",
    "byggelig",
    "kanskje",
    "komme",
    "lese",
    "like",
    "litt",
    "mye",
    "nå",
    "ofte",
    "på",
    "se",
    "sitte",
    "slappe av",
    "sliten",
    "spille",
    "studere",
    "treffe",
    "tykk",
    "unnskyld",
    "ved",
    "videre"
    ]
    let bundle2 = [
    "knihovna",
    "kniha",
    "den",
    "ovoce",
    "chuť",
    "lyže",
    "termoska",
    "čas",
    "výlet",
    "televize",
    "týden",
    "přítel",
    "přesto",
    "pracovat",
    "jenom",
    "lepší",
    "začít",
    "stát se",
    "bydlet",
    "tedy",
    "tebe",
    "toto",
    "líný",
    "pít",
    "nebo",
    "rozumět",
    "dělat",
    "jít",
    "jmenovat se",
    "domů",
    "každý",
    "kde",
    "milý",
    "třeba",
    "přijít",
    "číst",
    "mít rád",
    "trochu",
    "mnoho",
    "teď",
    "často",
    "v",
    "vidět",
    "sedět",
    "odpočinout si",
    "unavený",
    "hrát",
    "studovat",
    "potkat se",
    "tlustý",
    "promiň",
    "u",
    "dále"
    ]
    
    let bundle3Foreign = [
        "ei avis",
        "en brunost",
        "et brød",
        "en ettermiddag",
        "en familie",
        "en frokost",
        "et glass",
        "et hus",
        "en jobb",
        "ei klokke",
        "en kveld",
        "ei matpakke",
        "en middag",
        "ei midnatt",
        "en morgen",
        "en ost",
        "en politikk",
        "en pub",
        "ei polse",
        "ei seng",
        "en te",
        "en vie",
        "et øl",
        "bli",
        "der",
        "dra",
        "dusje",
        "etterpå",
        "fem",
        "fire",
        "for",
        "forskjellig",
        "før",
        "god",
        "ham",
        "heller ikke",
        "henne",
        "hos",
        "jo",
        "jobbe",
        "jogge",
        "kjøpe",
        "lage",
        "lenge",
        "ligge",
        "meg",
        "mellom",
        "neste",
        "ni",
        "noe",
        "når",
        "om",
        "oss",
        "ringe",
        "sammen",
        "seg",
        "seks",
        "si",
        "skrive",
        "snakke",
        "sove",
        "spise",
        "stå opp",
        "ta",
        "tidlig",
        "til",
        "tilbake",
        "vanligvis",
        "vaske",
        "vel"
    ]
    
    let bundle3 = [
        "noviny",
        "hnědý sýr",
        "chléb",
        "odpoledne",
        "rodina",
        "snídaně",
        "sklenice",
        "dům",
        "práce",
        "hodiny",
        "večer",
        "svačina",
        "oběd",
        "půlnoc",
        "ráno",
        "sýr",
        "politika",
        "hospoda",
        "salám",
        "postel",
        "čaj",
        "cesta",
        "pivo",
        "zůstat",
        "tam",
        "jet",
        "sprchovat",
        "potom",
        "pět",
        "čtyři",
        "pro",
        "různý",
        "před",
        "dobrý",
        "jeho",
        "také ne",
        "jí",
        "u",
        "ale ovšem",
        "pracovat",
        "běhat",
        "kupovat",
        "připravit",
        "dlouho",
        "ležet",
        "mě",
        "mezi",
        "další",
        "devět",
        "něco",
        "kdy",
        "o",
        "nás",
        "telefonovat",
        "spolu",
        "se",
        "šest",
        "říci",
        "psát",
        "mluvit",
        "spát",
        "jíst",
        "vstávat",
        "dát si",
        "brzy",
        "pro",
        "zpět",
        "obvykle",
        "mýt",
        "třeba"
    ]
    
    let bundle4Foreign = [
        "et besøk",
        "en billet",
        "en by",
        "en fot",
        "ei gate",
        "ei helg",
        "en hilsen",
        "et hjørne",
        "en jernabestasjon",
        "ei kirke",
        "en mann",
        "en plass",
        "et postkontor",
        "et postkort",
        "et rådhus",
        "en skole",
        "en spasertur",
        "en tale",
        "et teater",
        "en trikk",
        "et øyeblikk",
        "akkurat",
        "at",
        "behøve",
        "besøke",
        "billig",
        "burde",
        "bytte",
        "bør",
        "dit",
        "engelsk",
        "fin",
        "finne",
        "finnes",
        "forbi",
        "fordi",
        "fram",
        "først",
        "første",
        "få",
        "gjerne",
        "helt",
        "hilse",
        "hit",
        "hjelpe",
        "hvis",
        "høyre",
        "igjen",
        "jo",
        "kan",
        "kjære",
        "kjøre",
        "kunne",
        "lang",
        "langt",
        "lære",
        "må",
        "måtte",
        "nærheten",
        "om",
        "over",
        "overnatte",
        "reise",
        "rett",
        "rundt",
        "sant",
        "sees",
        "skulle",
        "skynde seg",
        "som",
        "spasere",
        "spørre",
        "stoppe",
        "svinge",
        "så",
        "ta",
        "treffes",
        "venstre",
        "verst",
        "vil",
        "ville",
        "vite"
    ]
    
    let bundle4 = [
        "návštěva",
        "lístek",
        "město",
        "noha",
        "ulice",
        "víkend",
        "pozdrav",
        "roh",
        "vlakové nádraží",
        "kostel",
        "muž",
        "místo",
        "pošta",
        "pohlednice",
        "radnice",
        "škola",
        "procházka",
        "řeč",
        "divadlo",
        "tramvaj",
        "okamžik",
        "právě",
        "že",
        "potřebovat",
        "navštívit",
        "levný",
        "mít povinnost",
        "přestoupit",
        "měl bych",
        "tam",
        "angličtina",
        "pěkný",
        "najít",
        "nalézat se",
        "kolem",
        "protože",
        "dopředu",
        "nejdříve",
        "první",
        "smět",
        "rád bych",
        "zcela",
        "zdravit",
        "sem",
        "pomoci",
        "kdyby",
        "pravý",
        "znovu",
        "přece",
        "mohu",
        "milý",
        "jet",
        "moci",
        "dlouhý",
        "daleko",
        "učit",
        "musím",
        "muset",
        "blízko",
        "jestli",
        "přes",
        "přenocovat",
        "cestovat",
        "rovný",
        "okolo",
        "pravda",
        "vidět se",
        "mít povinnost",
        "spěchat",
        "který",
        "procházet se",
        "ptát se",
        "zastavit",
        "zatočit",
        "pak",
        "trvat",
        "setkat se",
        "levý",
        "nejhorší",
        "já chci",
        "chtít",
        "vědět"
    ]
    
    let bundleJapaneseForeign1 = [
        "ひとつ",
        "ふたつ",
        "えん",
        "かね",
        "これ",
        "すいようび",
        "あれ",
        "さき",
        "ようか",
        "そば",
        "こっち",
        "みぎ",
        "あげる",
        "ここ",
        "とても",
        "なな",
        "て",
        "おなか",
        "すく",
        "ついたち",
        "にちようび",
        "ななつ",
        "どれ",
        "わたし",
        "すき",
        "ゲーム",
        "ひとり",
        "ともだち",
        "かえる",
        "げんき",
        "てんき",
        "すくない",
        "はれる",
        "うえ",
        "ドア",
        "ひらく",
        "くち",
        "しめる",
        "じかん",
        "むいか",
        "うしろ",
        "とおか",
        "ごぜん",
        "こんばん",
        "どようび",
        "きんようび",
        "つき",
        "よる",
        "たべる",
        "なに"
    ]
    
    let bundleJapanese1 = [
        "one (thing)",
        "two (things)",
        "yen",
        "money",
        "this, this one",
        "Wednesday",
        "that over there",
        "ahead, first",
        "eight days, 8th of the month",
        "side, vicinity",
        "here",
        "right",
        "give",
        "here",
        "very",
        "seven",
        "hand",
        "stomach",
        "be empty",
        "1st of the month",
        "Sunday",
        "seven (things)",
        "what, which",
        "I",
        "favorite, liked",
        "game",
        "one, one person",
        "friend, companion",
        "return, go back",
        "healthy, energetic",
        "weather",
        "few, little",
        "be sunny, clear up",
        "up, above",
        "door",
        "open",
        "mouth",
        "shut, close",
        "time, hour",
        "six days, 6th of the month",
        "back, behind",
        "ten days, 10th of the month",
        "morning, a.m.",
        "this evening, tonight",
        "Saturday",
        "Friday",
        "moon",
        "night (from sunset to sunrise)",
        "eat",
        "what, which"
    ]
    
    let romaji = ["a",
                    "i",
                    "u",
                    "e",
                    "o",
                    "ka",
                    "ki",
                    "ku",
                    "ke",
                    "ko",
                    "sa",
                    "shi",
                    "su",
                    "se",
                    "so",
                    "ta",
                    "chi",
                    "tsu",
                    "te",
                    "to",
                    "na",
                    "ni",
                    "nu",
                    "ne",
                    "no",
                    "ha",
                    "hi",
                    "fu",
                    "he",
                    "ho",
                    "ma",
                    "mi",
                    "mu",
                    "me",
                    "mo",
                    "ra",
                    "ri",
                    "ru",
                    "re",
                    "ro",
                    "wa",
                    "wo",
                    "n",
                    "ga",
                    "gi",
                    "gu",
                    "ge",
                    "go",
                    "za",
                    "ji",
                    "zu",
                    "ze",
                    "zo",
                    "da",
                    "ji",
                    "zu",
                    "de",
                    "do",
                    "ba",
                    "bi",
                    "bu",
                    "be",
                    "bo",
                    "pa",
                    "pi",
                    "pu",
                    "pe",
                    "po",
                    "ya",
                    "yu",
                    "yo",
                    "kya",
                    "kyu",
                    "kyo",
                    "sha",
                    "shu",
                    "sho",
                    "cha",
                    "chu",
                    "cho",
                    "nya",
                    "nyu",
                    "nyo",
                    "hya",
                    "hyu",
                    "hyo",
                    "mya",
                    "myu",
                    "myo",
                    "rya",
                    "ryu",
                    "ryo",
                    "gya",
                    "gyu",
                    "gyo",
                    "ja",
                    "ju",
                    "jo",
                    "bya",
                    "byu",
                    "byo",
                    "pya",
                    "pyu",
                    "pyo"
    ]
    
    let hirigana = [
        "あ",
        "い",
        "う",
        "え",
        "お",
        "か",
        "き",
        "く",
        "け",
        "こ",
        "さ",
        "し",
        "す",
        "せ",
        "そ",
        "た",
        "ち",
        "つ",
        "て",
        "と",
        "な",
        "に",
        "ぬ",
        "ね",
        "の",
        "は",
        "ひ",
        "ふ",
        "へ",
        "ほ",
        "ま",
        "み",
        "む",
        "め",
        "も",
        "ら",
        "り",
        "る",
        "れ",
        "ろ",
        "わ",
        "を",
        "ん",
        "が",
        "ぎ",
        "ぐ",
        "げ",
        "ご",
        "ざ",
        "じ",
        "ず",
        "ぜ",
        "ぞ",
        "だ",
        "ぢ",
        "づ",
        "で",
        "ど",
        "ば",
        "び",
        "ぶ",
        "べ",
        "ぼ",
        "ぱ",
        "ぴ",
        "ぷ",
        "ぺ",
        "ぽ",
        "や",
        "ゆ",
        "よ",
        "きゃ",
        "きゅ",
        "きょ",
        "しゃ",
        "しゅ",
        "しょ",
        "ちゃ",
        "ちゅ",
        "ちょ",
        "にゃ",
        "にゅ",
        "にょ",
        "ひゃ",
        "ひゅ",
        "ひょ",
        "みゃ",
        "みゅ",
        "みょ",
        "りゃ",
        "りゅ",
        "りょ",
        "ぎゃ",
        "ぎゅ",
        "ぎょ",
        "じゃ",
        "じゅ",
        "じょ",
        "びゃ",
        "びゅ",
        "びょ",
        "ぴゃ",
        "ぴゅ",
        "ぴょ",
    ]
    
    let aiueoCzech = [
        "déšť",
        "chodit",
        "pozdrav",
        "modrý",
        "podzim",
        "noha",
        "turnaj",
        "díra",
        "mravenec",
        "jeden",
        "venkov",
        "bolí",
        "úzký",
        "vlákno",
        "nyní",
        "význam",
        "kdy",
        "jít",
        "nahoře",
        "píseň",
        "šupina",
        "splávek",
        "prodat",
        "koupit",
        "fáma",
        "potkat",
        "recepce",
        "obraz",
        "zasadit",
        "dům",
        "krmivo",
        "přibýt",
        "límec",
        "žába",
        "jen",
        "obrázková knížka",
        "nádraží",
        "kopec",
        "příležitost",
        "skončit",
        "vůně",
        "zvláštní",
        "synovec",
        "vstát",
        "tlačit"
    ]
    
    let aiueoJapanese = [
        "あめ",
        "あるく",
        "あいさつ",
        "あおい",
        "あき",
        "あし",
        "しあい",
        "あな",
        "あり",
        "いち",
        "いなか",
        "いたい",
        "せまい",
        "いと",
        "いま",
        "いみ",
        "いつ",
        "いく",
        "うえ",
        "うた",
        "うろこ",
        "うき",
        "うる",
        "かう",
        "うわさ",
        "あう",
        "うけcうけ",
        "え",
        "うえる",
        "いえ",
        "えさ",
        "ふえる",
        "えり",
        "かえる",
        "えん",
        "えほん",
        "えき",
        "おか",
        "おり",
        "おわる",
        "かおり",
        "おもしろい",
        "おい",
        "おきる",
        "おす"
    ]
    
    let japaneseBasic1Czech = [
        "láska",
        "setkat se",
        "říct",
        "nahoru",
        "dům",
        "modrý",
        "červený",
        "podzim",
        "otevírat",
        "koupit",
        "psát",
        "jít",
        "tvář",
        "hlas",
        "nádraží",
        "ráno",
        "deštník",
        "noha",
        "židle",
        "kráva",
        "krajina",
        "hřeben",
        "zmáčknout",
        "sladkosti",
        "alkohol",
        "lež",
        "půjčit",
        "kvést",
        "sushi",
        "kámen"
    ]
    
    let japaneseBasic1 = [
        "あい",
        "あう",
        "いう",
        "うえ",
        "いえ",
        "あおい",
        "あかい",
        "あき",
        "あく",
        "かう",
        "かく",
        "いく",
        "かお",
        "こえ",
        "えき",
        "あさ",
        "かさ",
        "あし",
        "いす",
        "うし",
        "けしき",
        "くし",
        "おす",
        "おかし",
        "おさけ",
        "うそ",
        "かす",
        "さく",
        "おすし",
        "いし"
    ]
    
}
